# Generated by Django 4.1.5 on 2023-01-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_completiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completiondate',
            field=models.DateField(),
        ),
    ]
